#!/usr/bin/env python3
"""Generate a threshold-sweep round (phase 2) from a sweep spec.

Usage: gen_sweep.py <campaign_dir> <sweep_name>

Reads rounds/<sweep_name>/spec.json:
  { "entries": [ { "tokens": ["f21","f22"], "act": [-13,-11,...] }, ... ] }

Each (token-set, act) pair becomes one config. Pos/neg train thresholds stay
at the N-feature rule values (protocol thresholds_by_n) — the activation
threshold is the only swept knob, so each entry traces a precision-recall
curve for one feature set. Keys are "<canonical-set>|act=<A>" so they never
collide with the beam memo. Writes exp.yml + manifest.json next to the spec.
"""
import json
import os
import sys

import yaml

BASE_ARGS = (
    "--warmup_instructions={warm} --simulation_instructions={sim} "
    "--llc_replacement_type=ship "
    "--config=$(SIM_HOME_IN_CLUSTER)/config/nopref.ini "
    "--num_rob_partitions=3 --rob_partition_size=64,128,320 "
    "--rob_frontal_partition_ids=0 --rob_dorsal_partition_ids=2"
)
PYTHIA = (
    "--l2c_prefetcher_types=scooby "
    "--config=$(SIM_HOME_IN_CLUSTER)/config/pythia.ini "
    "--scooby_enable_direct_pref_issue=true --scooby_pref_at_lower_level=true "
    "--scooby_dyn_degrees_type2=1,1,2,4"
)
OCP_UNCORE = (
    "--config=$(SIM_HOME_IN_CLUSTER)/config/ocp_hermes.ini "
    "--offchip_pred_location=uncore"
)
HERMES = "--config=$(SIM_HOME_IN_CLUSTER)/config/hermes_base.ini --ddrp_req_latency=1"
NONREGION_SIZE_FILL = 21


def tok_parse(s):
    if "@" in s:
        f, z = s.split("@")
        return (int(f[1:]), int(z))
    return (int(s[1:]), None)


def main():
    cdir = os.path.abspath(sys.argv[1])
    name = sys.argv[2]
    proto = yaml.safe_load(open(os.path.join(cdir, "protocol.yml")))
    rdir = os.path.join(cdir, "rounds", name)
    spec = json.load(open(os.path.join(rdir, "spec.json")))
    wt = proto["system"]["window_tuning"]
    fixed = proto["fixed_knobs"]
    phys = (" --ocp_perc_use_physical_address=true"
            if proto["system"]["address_space"] == "physical" else "")

    lines = [
        "---",
        f"# campaign1 {name} — generated by gen_sweep.py (DO NOT EDIT BY HAND)",
        "definitions:",
        f'  - TBASE: "{BASE_ARGS.format(warm=wt["warmup"], sim=wt["sim"])}"',
        f'  - PYTHIA: "{PYTHIA}"',
        f'  - OCP_UNCORE: "{OCP_UNCORE}"',
        f'  - HERMES: "{HERMES}"',
        "experiments:",
    ]
    manifest = {}
    idx = 0
    for entry in spec["entries"]:
        n = len(entry["tokens"])
        # optional per-entry overrides (default: campaign fixed knobs / N-rule);
        # weight_sizes are written in the ENTRY's token order and sorted along
        # with the tokens into canonical order
        in_sizes = entry.get("weight_sizes",
                             [fixed["weight_array_size_per_feature"]] * n)
        assert len(in_sizes) == n, f"weight_sizes must have {n} entries"
        pairs = sorted(zip((tok_parse(t) for t in entry["tokens"]), in_sizes),
                       key=lambda p: (p[0][0], -1 if p[0][1] is None else p[0][1]))
        toks = [p[0] for p in pairs]
        sizes = [p[1] for p in pairs]
        key_set = "+".join(f"f{f}" if z is None else f"f{f}@{z}" for f, z in toks)
        thr = proto["thresholds_by_n"][n]
        feats = ",".join(str(f) for f, _ in toks)
        wts = ",".join(str(s) for s in sizes)
        pos = entry.get("pos_train", thr[1])
        neg = entry.get("neg_train", thr[2])
        hsh = ",".join(str(fixed["feature_hash_type"]) for _ in toks)
        rsz = ",".join(str(NONREGION_SIZE_FILL if z is None else z) for _, z in toks)
        keyx = ""
        if "weight_sizes" in entry:
            keyx += "|w=" + "x".join(str(s) for s in sizes)
        if "pos_train" in entry or "neg_train" in entry:
            keyx += f"|tr={pos}/{neg}"
        for act in entry["act"]:
            en = f"{name}_c{idx:03d}"
            idx += 1
            args = (f"$(TBASE) $(PYTHIA) $(OCP_UNCORE){phys} "
                    f"--ocp_perc_activated_features={feats} "
                    f"--ocp_perc_weight_array_sizes={wts} "
                    f"--ocp_perc_feature_hash_types={hsh} "
                    f"--ocp_perc_feature_region_size_log2s={rsz} "
                    f"--ocp_perc_activation_threshold={act} "
                    f"--ocp_perc_pos_train_thresh={pos} "
                    f"--ocp_perc_neg_train_thresh={neg} "
                    f"$(HERMES)")
            lines.append(f"  - {en} : {args}")
            manifest[en] = {"key": f"{key_set}|act={act}{keyx}",
                            "tokens": entry["tokens"],
                            "window": "tuning", "role": "config"}
    with open(os.path.join(rdir, "exp.yml"), "w") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(rdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    traces = yaml.safe_load(open(proto["system"]["tlist"]))
    ntraces = len(next(iter(traces.values())))
    print(f"{name}: configs={idx} jobs={idx*ntraces}")


if __name__ == "__main__":
    main()
