---
abstract: 'Perl interface to PARI.'
author:
  - 'Ilya Zakharevich <ilyaz@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Pari
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.030518
